### PR TITLE
implement radix sort

### PR DESCRIPTION
**Pull request by psolaimani**

### CODE REVIEW

**Comment by akbertram** [comment]
@psolaimani is this PR still relevant or can we close?

**Comment by psolaimani** [comment]
Depends. If we want to solve the issues with packages we can add 'radix' option to `sort()` formal 'method' and further ignore it. Or do we want to implement `radixsort` and compare the performance.

**Comment by akbertram** [comment]
I'd say let's update the R code to accept the 'radix' argument but would further not prioritize implementing the algorithm.

**Comment by psolaimani** [comment]
retest this please

**Pull request merged**
