### PR TITLE
mode r as alias for rb and modes w/wb

### PR DESCRIPTION
**Pull request by Alain-Bearez**
Mode `r ` is just an alias for mode `rb`.

Modes `w` and `wb` introduce the `write` counterpart of `read`.

### CODE REVIEW

**Comment by akbertram** [comment]
@psolaimani is also working on this at the moment. We had some questions about how faithfully we want to handle line-ending translations on Windows.

**Comment by psolaimani** [comment]
@Alain-Bearez Thanks. the `r` mode should handle EOL conversions. But if this solves your issue and the build passes, we can merge it in as an initial implementation.

**Comment by Alain-Bearez** [comment]
I have not been working with C or Windows in the last few years, but my understanding was that these EOL considerations occur only when using `fgets` and `fputs`, which are not part of this PR.

I had only read the docs for POSIX systems where the `b` is ignored. Sorry for my precipitation. But it worked for me... :D

Anyhow, this will be quite difficult to implement since the handling of EOL is taken care by the `Reader` and `Printer` subclasses not the `InputStream` and `OutputStream` hierarchy...

**Comment by akbertram** [comment]
Yeah... there's also the question of character sets, etc. We would need a sort of FilterInputStream with a single byte read-ahead buffer to handle EOL conversion, with the assumption that the input stream has a single-byte encoding compatible with ASCII. Yeck. This is great for now!

**Pull request merged**
