### PR TITLE
implement rapply 

### PR DESCRIPTION
**Pull request by Alain-Bearez**
This is my attempt to resolve issue #362 with three tests for values `list`, `unlist`  and `replace` of `how` parameter.

### CODE REVIEW

**Comment by akbertram** [comment]
@bddbot add to whitelist

**Comment by akbertram** [comment]
There is one test failing:
http://build.renjin.org/job/renjin-pull-requests/547/testReport/junit/test/rapply/rapply_1/

It also fails in GNU R, so I think it's just the way it's written:
```
> rapply(l, f, clz, deflt = 123, how = "unlist")
  first second1 second2 second3   third fourth1 fourth2 
    123     123     123     123     123     123     123 
```
Your expectation is just missing the names.

Please remove the Java test code when you're done.

**Comment by Alain-Bearez** [comment]
It is not just the names.

I am expecting the first three values to be -2, -4 and -6 as they were numbers that the function should have multiplied by -2.

I will check if the other two tests fail in the same way.

**Comment by akbertram** [comment]
FYI:  I have written a little Intellij plugin that allows you to right click and run tests written in R from the editor, it can be helpful in writing tests like this. You can download the build from here:
http://build.renjin.org/job/renjin-idea/

**Comment by Alain-Bearez** [comment]
Way better than wait for the whole maven build to fail!

I got the tests to pass from Maven and compared with the results in RStudio. 

⁣I will push after I finish my day work. 


-------- Oorspronkelijk bericht --------
Van: Alex Bertram <notifications@github.com>
Verzonden: Fri Dec 08 03:08:30 GMT-03:00 2017
Aan: bedatadriven/renjin <renjin@noreply.github.com>
Cc: "Alain Béarez" <abearez@for-scala.it>, Author <author@noreply.github.com>
Onderwerp: Re: [bedatadriven/renjin] implement rapply (#363)

FYI:  I have written a little Intellij plugin that allows you to right click and run tests written in R from the editor, it can be helpful in writing tests like this. You can download the build from here:
http://build.renjin.org/job/renjin-idea/

**Pull request merged**
