### PR TITLE
Adds some namespace related functions.

### PR DESCRIPTION
**Pull request by hlin09**
Adds `getNamespaceName`, `getNamespaceExports`, `getNamespaceImports`.

### CODE REVIEW

**Comment by akbertram** [comment]
@bddbot please retest

**Comment by akbertram** [comment]
retest this please

**Comment by akbertram** [comment]
@bddbot retest this please

**Comment by akbertram** [comment]
@bddbot retest this please

**Comment by akbertram** [comment]
Sorry I haven't merged this in yet; it looks good, very clean, but I wanted to make sure it was covered with tests first. I've added some here: https://github.com/bedatadriven/renjin/tree/hlin09-namespaceFunc

But it looks like getNamespaceExports() doesn't quite work with the base package yet. If you can take a look and add a test for getNamespaceExports() then will merge asap!

**Comment by hlin09** [comment]
Thanks for bringing it up. I will look into it when I have time in these
two days :)

**Comment by akbertram** [comment]
Terrific!

**Comment by hlin09** [comment]
Thanks @akbertram for reviewing. Since we are treating base package specially, I have just added a check for this case. Your unit test should work now. Please let me know if there is more issues.

**Comment by akbertram** [comment]
This is failing one of the tests because the attributes don't match the output of GNU R. I've also been looking at the docs and it seems these functions are meant to support character arguments like `getNamespaceExports("stats")` in addition to namespace environment. I've fixed both issues here: https://github.com/bedatadriven/renjin/tree/hlin09-namespaceFunc

However, it looks like `getNamespaceExports()` also returns a result quite different than GNU R. This is what I get from GNU R 3.2:

```
> getNamespaceImports("stats")
$base
[1] TRUE

$graphics
        assocplot             title         axis.Date            points 
      "assocplot"           "title"       "axis.Date"          "points" 
   
$grDevices
  dev.interactive           palette       extendrange         xy.coords 
"dev.interactive"         "palette"     "extendrange"       "xy.coords" 

$utils
  str 
"str" 
```

Where as your implementation only returns a character vector. Do you need this function or should we just remove until we can implement it properly?

**Comment by hlin09** [comment]
Hi Alex,

Thanks a lot for the fix! I would say let's wait until it is correctly
implemented, as I will not need this badly for now. Or you can commit other
functions if possible. Either will work for me. I will take a look at this
Imports function later. Sorry for the trouble.

Hao

**Pull request merged**
