### PR TITLE
Fix deseq2 related issues

### PR DESCRIPTION
**Pull request by psolaimani**
fixing issues that block build of simplified DESeq2 package

### CODE REVIEW

**Comment by psolaimani** [comment]
[Here](https://github.com/bedatadriven/renjin/blob/6089bb33fd70e56e4f15bfbf645814c25b968ca8/tools/gcc-bridge/compiler/src/main/java/org/renjin/gcc/codegen/type/record/RecordArrayExpr.java#L57) the **rhs** is `FatPtrPair` and is being cast to `RecordArrayExpr`

[Here](https://github.com/bedatadriven/DESeq2/blob/master/src/DESeq2.cpp#L382) is the line of code that results in this error. 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.666 s
[INFO] Finished at: 2017-03-07T14:56:39+01:00
[INFO] Final Memory: 18M/459M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.renjin:renjin-maven-plugin:0.9.0-SNAPSHOT:gnur-compile (compile) on project DESeq2: Compilation of GNU R sources failed: Failed to compile Gimple: Exception compiling function fitDispGrid [_Z11fitDispGridP7SEXPRECS0_S0_S0_S0_S0_S0_] in unit DESeq2.gimple: Exception compiling instruction T582276 = &_ZN4arma5zerosEj(T638235): org.renjin.gcc.codegen.fatptr.FatPtrPair cannot be cast to org.renjin.gcc.codegen.type.record.RecordArrayExpr -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.renjin:renjin-maven-plugin:0.9.0-SNAPSHOT:gnur-compile (compile) on project DESeq2: Compilation of GNU R sources failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Compilation of GNU R sources failed
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:75)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.renjin.packaging.BuildException: Compilation of GNU R sources failed
	at org.renjin.packaging.PackageBuilder.compileNativeSources(PackageBuilder.java:82)
	at org.renjin.packaging.PackageBuilder.build(PackageBuilder.java:50)
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:69)
	... 23 more
Caused by: org.renjin.packaging.BuildException: Failed to compile Gimple
	at org.renjin.packaging.NativeSourceBuilder.compileGimple(NativeSourceBuilder.java:201)
	at org.renjin.packaging.NativeSourceBuilder.build(NativeSourceBuilder.java:67)
	at org.renjin.packaging.PackageBuilder.compileNativeSources(PackageBuilder.java:76)
	... 25 more
Caused by: org.renjin.gcc.InternalCompilerException: Exception compiling function fitDispGrid [_Z11fitDispGridP7SEXPRECS0_S0_S0_S0_S0_S0_] in unit DESeq2.gimple
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:239)
	at org.renjin.gcc.codegen.UnitClassGenerator.emit(UnitClassGenerator.java:165)
	at org.renjin.gcc.GimpleCompiler.compile(GimpleCompiler.java:234)
	at org.renjin.packaging.NativeSourceBuilder.compileGimple(NativeSourceBuilder.java:199)
	... 27 more
Caused by: org.renjin.gcc.InternalCompilerException: Exception compiling instruction T582276 = &_ZN4arma5zerosEj(T638235)
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:312)
	at org.renjin.gcc.codegen.FunctionGenerator.emit(FunctionGenerator.java:146)
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:237)
	... 30 more
Caused by: java.lang.ClassCastException: org.renjin.gcc.codegen.fatptr.FatPtrPair cannot be cast to org.renjin.gcc.codegen.type.record.RecordArrayExpr
	at org.renjin.gcc.codegen.type.record.RecordArrayExpr.store(RecordArrayExpr.java:57)
	at org.renjin.gcc.codegen.call.FunctionCallGenerator.emitCall(FunctionCallGenerator.java:94)
	at org.renjin.gcc.codegen.FunctionGenerator.emitCall(FunctionGenerator.java:377)
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:305)
	... 32 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by akbertram** [comment]
@psolaimani do you know the C/C++ types that are being assigned? Is it a superclass to subclass or vice-versa?

**Comment by akbertram** [comment]
@psolaimani can you remove the `-fno-elide-constructors` flag if it didn't help?

**Comment by psolaimani** [comment]
retest please @bddbot

**Comment by akbertram** [comment]
Are we there yet? Are we there yet? Are we there yet? :-)

**Comment by psolaimani** [comment]
not so fast ;-)

we are here:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.053 s
[INFO] Finished at: 2017-03-15T09:39:49+01:00
[INFO] Final Memory: 18M/433M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.renjin:renjin-maven-plugin:0.9.0-SNAPSHOT:gnur-compile (compile) on project DESeq2: Compilation of GNU R sources failed: Failed to compile Gimple: Exception compiling function __base_ctor  [_ZN4Rcpp6traits12named_objectIN4arma3ColIdEEEC2ERKSsRKS4_] in unit DESeq2.gimple: Exception compiling instruction *this.object = o_			#37: Exception compiling assignment to *this.object = o_			#37: TODO: strategy = RecordUnitPtrStrategy[Col] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.renjin:renjin-maven-plugin:0.9.0-SNAPSHOT:gnur-compile (compile) on project DESeq2: Compilation of GNU R sources failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Compilation of GNU R sources failed
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:75)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.renjin.packaging.BuildException: Compilation of GNU R sources failed
	at org.renjin.packaging.PackageBuilder.compileNativeSources(PackageBuilder.java:82)
	at org.renjin.packaging.PackageBuilder.build(PackageBuilder.java:50)
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:69)
	... 23 more
Caused by: org.renjin.packaging.BuildException: Failed to compile Gimple
	at org.renjin.packaging.NativeSourceBuilder.compileGimple(NativeSourceBuilder.java:201)
	at org.renjin.packaging.NativeSourceBuilder.build(NativeSourceBuilder.java:67)
	at org.renjin.packaging.PackageBuilder.compileNativeSources(PackageBuilder.java:76)
	... 25 more
Caused by: org.renjin.gcc.InternalCompilerException: Exception compiling function __base_ctor  [_ZN4Rcpp6traits12named_objectIN4arma3ColIdEEEC2ERKSsRKS4_] in unit DESeq2.gimple
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:239)
	at org.renjin.gcc.codegen.UnitClassGenerator.emit(UnitClassGenerator.java:165)
	at org.renjin.gcc.GimpleCompiler.compile(GimpleCompiler.java:234)
	at org.renjin.packaging.NativeSourceBuilder.compileGimple(NativeSourceBuilder.java:199)
	... 27 more
Caused by: org.renjin.gcc.InternalCompilerException: Exception compiling instruction *this.object = o_			#37
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:312)
	at org.renjin.gcc.codegen.FunctionGenerator.emit(FunctionGenerator.java:146)
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:237)
	... 30 more
Caused by: java.lang.RuntimeException: Exception compiling assignment to *this.object = o_			#37
	at org.renjin.gcc.codegen.FunctionGenerator.emitAssignment(FunctionGenerator.java:354)
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:297)
	... 32 more
Caused by: java.lang.UnsupportedOperationException: TODO: strategy = RecordUnitPtrStrategy[Col]
	at org.renjin.gcc.codegen.type.record.PointerUnionField.memberExpr(PointerUnionField.java:60)
	at org.renjin.gcc.codegen.type.record.RecordClassLayout.memberOf(RecordClassLayout.java:207)
	at org.renjin.gcc.codegen.type.record.RecordClassTypeStrategy.memberOf(RecordClassTypeStrategy.java:138)
	at org.renjin.gcc.codegen.type.record.RecordClassTypeStrategy.memberOf(RecordClassTypeStrategy.java:44)
	at org.renjin.gcc.codegen.expr.ExprFactory.findGenerator(ExprFactory.java:177)
	at org.renjin.gcc.codegen.FunctionGenerator.emitAssignment(FunctionGenerator.java:348)
	... 33 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by akbertram** [comment]
Here is a test case I think:
```.c
struct A {
   int x;
   double y;
}
union B {
  int *pi;
  struct A *pa;
}

void test_rup() {
  struct A a;
  a.x = 41;
  a.y = 1.2;
 
  union B b;
  b.pa =  &a;

  ASSERT(b.pa->x == 41);
  ASSERT(b.pa->y == 1.2);
}

void test_intptr() {
  int i = 44;
  union B b;
  b.pi = &i;
  
  ASSERT( *(b.pi) == 44);
}
```

When we have a union of pointers of different type, we use the PointerUnionField strategy, which compiles the field to a single field of type `java.lang.Object`. 

So you need to add a case for RecordUnitPointers that casts the object field to the correct type.

**Pull request merged**
